name: "Build & Test (nix)"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build & check
      run: |
        nix build
        nix flake check
    - name: "Upload coverage report"
      uses: actions/upload-artifact@v3
      with:
        name: html-coverage
        path: htmlcov/
